
const products = [
  {
    id: 1,
    name: "Toyota Corolla",
    price: "$18 000",
    image: "/images/car1.jpeg",
    category: "cars",
  },
  {
    id: 2,
    name: "Honda Fit",
    price: "$12 500",
    image: "/images/car2.jpeg",
    category: "cars",
  },
  {
    id: 3,
    name: "Bridgestone Tyre",
    price: "$150",
    image: "/images/car3.jpeg",
    category: "tyres",
  },
  {
    id: 4,
    name: "Car Battery",
    price: "$200",
    image: "/images/car4.jpeg",
    category: "batteries",
  },
  {
    id: 5,
    name: "Toyota Corolla",
    price: "$18 000",
    image: "/images/car5.jpeg",
    category: "cars",
  },
  {
    id: 6,
    name: "Toyota Corolla",
    price: "$18 000",
    image: "/images/car6.jpeg",
    category: "cars",
  },
  {
    id: 7,
    name: "Toyota Corolla",
    price: "$18 000",
    image: "/images/car7.jpeg",
    category: "cars",
  },
  {
    id: 8,
    name: "Toyota Corolla",
    price: "$18 000",
    image: "/images/car8.jpeg",
    category: "cars",
  },
  {
    id: 9,
    name: "Toyota Corolla",
    price: "$18 000",
    image: "/images/car9.jpeg",
    category: "cars",
  },
  {
    id: 10,
    name: "Toyota Corolla",
    price: "$18 000",
    image: "/images/car10.jpeg",
    category: "cars",
  },
  {
    id: 11,
    name: "Toyota Corolla",
    price: "$18 000",
    image: "/images/car11.jpeg",
    category: "cars",
  },
  {
    id: 12,
    name: "Toyota Corolla",
    price: "$18 000",
    image: "/images/car12.jpeg",
    category: "tyres",
  },
  {
    id: 13,
    name: "Toyota Corolla",
    price: "$18 000",
    image: "/images/car13.jpeg",
    category: "cars",
  },
  {
    id: 14,
    name: "Toyota Corolla",
    price: "$18 000",
    image: "/images/car14.jpeg",
    category: "cars",
  },
  {
    id: 15,
    name: "Toyota Corolla",
    price: "$18 000",
    image: "/images/car15.jpeg",
    category: "tyres",
  },
  {
    id: 16,
    name: "Toyota Corolla",
    price: "$18 000",
    image: "/images/car16.jpeg",
    category: "tyres",
  },
  {
    id: 17,
    name: "Toyota Corolla",
    price: "$18 000",
    image: "/images/car17.jpeg",
    category: "tyres",
  },
  {
    id: 40,
    name: "Toyota Corolla",
    price: "$18 000",
    image: "/images/car40.jpeg",
    category: "tyres",
  },
  {
    id: 18,
    name: "Toyota Corolla",
    price: "$18 000",
    image: "/images/car18.jpeg",
    category: "tyres",
  },
  {
    id: 19,
    name: "Toyota Corolla",
    price: "$18 000",
    image: "/images/car19.jpeg",
    category: "tyres",
  },
  {
    id: 20,
    name: "Toyota Corolla",
    price: "$18 000",
    image: "/images/car20.jpeg",
    category: "tyres",
  },
  {
    id: 21,
    name: "Toyota Corolla",
    price: "$18 000",
    image: "/images/car21.jpeg",
    category: "batteries",
  },
  {
    id: 22,
    name: "Toyota Corolla",
    price: "$18 000",
    image: "/images/car22.jpeg",
    category: "batteries",
  },
  {
    id: 23,
    name: "Toyota Corolla",
    price: "$18 000",
    image: "/images/car23.jpeg",
    category: "batteries",
  },
  {
    id: 24,
    name: "Toyota Corolla",
    price: "$18 000",
    image: "/images/car24.jpeg",
    category: "batteries",
  },
  {
    id: 25,
    name: "Toyota Corolla",
    price: "$18 000",
    image: "/images/car25.jpeg",
    category: "batteries",
  },
  {
    id: 26,
    name: "Toyota Corolla",
    price: "$18 000",
    image: "/images/car26.jpeg",
    category: "batteries",
  },
  {
    id: 27,
    name: "Toyota Corolla",
    price: "$18 000",
    image: "/images/car27.jpeg",
    category: "batteries",
  },
  {
    id: 28,
    name: "Toyota Corolla",
    price: "$18 000",
    image: "/images/car28.jpeg",
    category: "seats",
  },
  {
    id: 29,
    name: "Toyota Corolla",
    price: "$18 000",
    image: "/images/car29.jpeg",
    category: "seats",
  },
  {
    id: 30,
    name: "Toyota Corolla",
    price: "$18 000",
    image: "/images/car30.jpeg",
    category: "seats",
  },
  {
    id: 31,
    name: "Toyota Corolla",
    price: "$18 000",
    image: "/images/car31.jpeg",
    category: "seats",
  },
  {
    id: 32,
    name: "Toyota Corolla",
    price: "$18 000",
    image: "/images/car32.jpeg",
    category: "seats",
  },
  {
    id: 33,
    name: "Toyota Corolla",
    price: "$18 000",
    image: "/images/car33.jpeg",
    category: "seats",
  },
  {
    id: 34,
    name: "Toyota Corolla",
    price: "$18 000",
    image: "/images/car34.jpeg",
    category: "seats",
  },
  {
    id: 35,
    name: "Toyota Corolla",
    price: "$18 000",
    image: "/images/car35.jpeg",
    category: "seats",
  },
  {
    id: 36,
    name: "Toyota Corolla",
    price: "$18 000",
    image: "/images/car36.jpeg",
    category: "oil",
  },
  {
    id: 37,
    name: "Toyota Corolla",
    price: "$18 000",
    image: "/images/car37.jpeg",
    category: "oil",
  },
  {
    id: 38,
    name: "Toyota Corolla",
    price: "$18 000",
    image: "/images/car38.jpeg",
    category: "oil",
  },
  {
    id: 39,
    name: "Toyota Corolla",
    price: "$18 000",
    image: "/images/car39.jpeg",
    category: "oil",
  },
];

module.exports = products;